import 'package:kali_on_debian/kali_tools/select_tools_to_install.dart';

enum KaliToolsInformationGatheringEnum {
  Otrace,
  arping_iputils_arping,
  braa,
  dmitry,
  dnsenum,
  dnsmap,
  dnsrecon,
  dnstracer,
  dnswalk,
  enum4linux,
  fierce,
  firewalk,
  fping,
  fragrouter,
  ftester,
  hping3,
  ike_scan,
  intrace,
  irpas,
  lbd,
  legion,
  maltego,
  masscan,
  metagoofil,
  nbtscan,
  ncat,
  netdiscover,
  netmask,
  nmap,
  onesixtyone,
  p0f,
  qsslcaudit,
  recon_ng,
  smbmap,
  smtp_user_enum,
  snmpcheck,
  ssldump,
  sslh,
  sslscan,
  sslyze,
  swaks,
  thc_ipv6,
  theharvester,
  tlssled,
  twofi,
  unicornscan,
  urlcrazy,
  wafw00f,
  zenmap,
}

Map<KaliToolsInformationGatheringEnum, String> _kaliToolsInformationGatheringMap = {
  KaliToolsInformationGatheringEnum.Otrace: '0trace',
  KaliToolsInformationGatheringEnum.arping_iputils_arping: 'arping | iputils-arping',
  KaliToolsInformationGatheringEnum.braa: 'braa',
  KaliToolsInformationGatheringEnum.dmitry: 'dmitry',
  KaliToolsInformationGatheringEnum.dnsenum: 'dnsenum',
  KaliToolsInformationGatheringEnum.dnsmap: 'dnsmap',
  KaliToolsInformationGatheringEnum.dnsrecon: 'dnsrecon',
  KaliToolsInformationGatheringEnum.dnstracer: 'dnstracer',
  KaliToolsInformationGatheringEnum.dnswalk: 'dnswalk',
  KaliToolsInformationGatheringEnum.enum4linux: 'enum4linux',
  KaliToolsInformationGatheringEnum.fierce: 'fierce',
  KaliToolsInformationGatheringEnum.firewalk: 'firewalk',
  KaliToolsInformationGatheringEnum.fping: 'fping',
  KaliToolsInformationGatheringEnum.fragrouter: 'fragrouter',
  KaliToolsInformationGatheringEnum.ftester: 'ftester',
  KaliToolsInformationGatheringEnum.hping3: 'hping3',
  KaliToolsInformationGatheringEnum.ike_scan: 'ike-scan',
  KaliToolsInformationGatheringEnum.intrace: 'intrace',
  KaliToolsInformationGatheringEnum.irpas: 'irpas',
  KaliToolsInformationGatheringEnum.lbd: 'lbd',
  KaliToolsInformationGatheringEnum.legion: 'legion',
  KaliToolsInformationGatheringEnum.maltego: 'maltego',
  KaliToolsInformationGatheringEnum.masscan: 'masscan',
  KaliToolsInformationGatheringEnum.metagoofil: 'metagoofil',
  KaliToolsInformationGatheringEnum.nbtscan: 'nbtscan',
  KaliToolsInformationGatheringEnum.ncat: 'ncat',
  KaliToolsInformationGatheringEnum.netdiscover: 'netdiscover',
  KaliToolsInformationGatheringEnum.netmask: 'netmask',
  KaliToolsInformationGatheringEnum.nmap: 'nmap',
  KaliToolsInformationGatheringEnum.onesixtyone: 'onesixtyone',
  KaliToolsInformationGatheringEnum.p0f: 'p0f',
  KaliToolsInformationGatheringEnum.qsslcaudit: 'qsslcaudit',
  KaliToolsInformationGatheringEnum.recon_ng: 'recon-ng',
  KaliToolsInformationGatheringEnum.smbmap: 'smbmap',
  KaliToolsInformationGatheringEnum.smtp_user_enum: 'smtp-user-enum',
  KaliToolsInformationGatheringEnum.snmpcheck: 'snmpcheck',
  KaliToolsInformationGatheringEnum.ssldump: 'ssldump',
  KaliToolsInformationGatheringEnum.sslh: 'sslh',
  KaliToolsInformationGatheringEnum.sslscan: 'sslscan',
  KaliToolsInformationGatheringEnum.sslyze: 'sslyze',
  KaliToolsInformationGatheringEnum.swaks: 'swaks',
  KaliToolsInformationGatheringEnum.thc_ipv6: 'thc-ipv6',
  KaliToolsInformationGatheringEnum.theharvester: 'theharvester',
  KaliToolsInformationGatheringEnum.tlssled: 'tlssled',
  KaliToolsInformationGatheringEnum.twofi: 'twofi',
  KaliToolsInformationGatheringEnum.unicornscan: 'unicornscan',
  KaliToolsInformationGatheringEnum.urlcrazy: 'urlcrazy',
  KaliToolsInformationGatheringEnum.wafw00f: 'wafw00f',
  KaliToolsInformationGatheringEnum.zenmap: 'zenmap',
};

extension KaliToolsInformationGatheringEnumExt on KaliToolsInformationGatheringEnum {
  String get package {
    switch (this) {
      default:
        return _kaliToolsInformationGatheringMap[this]!;
    }
  }
}

Future<ToolSelectionResult> selectKaliToolsInformationGatheringToInstall() =>
    selectToolsToInstall<KaliToolsInformationGatheringEnum>(
      groupName: 'kali-tools-information-gathering',
      values: KaliToolsInformationGatheringEnum.values,
      packageNameGetter: (e) => e.package,
    );
