import 'package:kali_on_debian/services/select_tools_to_install.dart';

enum KaliToolsWebEnum {
  apacheUsers,
  apache2,
  beefXss,
  burpsuite,
  cadaver,
  commix,
  cutycapt,
  davtest,
  defaultMysqlServer,
  dirb,
  dirbuster,
  dotdotpwn,
  eyewitness,
  ferretSidejack,
  ftester,
  hakrawler,
  hamsterSidejack,
  heartleech,
  httprint,
  httrack,
  hydra,
  jbossAutopwn,
  joomscan,
  jsqlInjection,
  laudanum,
  lbd,
  maltego,
  medusa,
  mitmproxy,
  ncrack,
  nikto,
  nishang,
  nmap,
  oscanner,
  owaspMantraFf,
  padbuster,
  paros,
  patator,
  php,
  phpMysql,
  proxychains4,
  proxytunnel,
  qsslcaudit,
  redsocks,
  sidguesser,
  siege,
  skipfish,
  slowhttptest,
  sqldict,
  sqlitebrowser,
  sqlmap,
  sqlninja,
  sqlsus,
  ssldump,
  sslh,
  sslscan,
  sslsniff,
  sslsplit,
  sslyze,
  stunnel4,
  thcSslDos,
  tlssled,
  tnscmd10g,
  uniscan,
  wafw00f,
  wapiti,
  watobo,
  webacoo,
  webscarab,
  webshells,
  weevely,
  wfuzz,
  whatweb,
  wireshark,
  wpscan,
  xsser,
  zaproxy,
}

Map<KaliToolsWebEnum, String> _kaliToolsWebMap = {
  KaliToolsWebEnum.apacheUsers: 'apache-users',
  KaliToolsWebEnum.apache2: 'apache2',
  KaliToolsWebEnum.beefXss: 'beef-xss',
  KaliToolsWebEnum.burpsuite: 'burpsuite',
  KaliToolsWebEnum.cadaver: 'cadaver',
  KaliToolsWebEnum.commix: 'commix',
  KaliToolsWebEnum.cutycapt: 'cutycapt',
  KaliToolsWebEnum.davtest: 'davtest',
  KaliToolsWebEnum.defaultMysqlServer: 'default-mysql-server',
  KaliToolsWebEnum.dirb: 'dirb',
  KaliToolsWebEnum.dirbuster: 'dirbuster',
  KaliToolsWebEnum.dotdotpwn: 'dotdotpwn',
  KaliToolsWebEnum.eyewitness: 'eyewitness',
  KaliToolsWebEnum.ferretSidejack: 'ferret-sidejack',
  KaliToolsWebEnum.ftester: 'ftester',
  KaliToolsWebEnum.hakrawler: 'hakrawler',
  KaliToolsWebEnum.hamsterSidejack: 'hamster-sidejack',
  KaliToolsWebEnum.heartleech: 'heartleech',
  KaliToolsWebEnum.httprint: 'httprint',
  KaliToolsWebEnum.httrack: 'httrack',
  KaliToolsWebEnum.hydra: 'hydra',
  KaliToolsWebEnum.jbossAutopwn: 'jboss-autopwn',
  KaliToolsWebEnum.joomscan: 'joomscan',
  KaliToolsWebEnum.jsqlInjection: 'jsql-injection',
  KaliToolsWebEnum.laudanum: 'laudanum',
  KaliToolsWebEnum.lbd: 'lbd',
  KaliToolsWebEnum.maltego: 'maltego',
  KaliToolsWebEnum.medusa: 'medusa',
  KaliToolsWebEnum.mitmproxy: 'mitmproxy',
  KaliToolsWebEnum.ncrack: 'ncrack',
  KaliToolsWebEnum.nikto: 'nikto',
  KaliToolsWebEnum.nishang: 'nishang',
  KaliToolsWebEnum.nmap: 'nmap',
  KaliToolsWebEnum.oscanner: 'oscanner',
  KaliToolsWebEnum.owaspMantraFf: 'owasp-mantra-ff',
  KaliToolsWebEnum.padbuster: 'padbuster',
  KaliToolsWebEnum.paros: 'paros',
  KaliToolsWebEnum.patator: 'patator',
  KaliToolsWebEnum.php: 'php',
  KaliToolsWebEnum.phpMysql: 'php-mysql',
  KaliToolsWebEnum.proxychains4: 'proxychains4',
  KaliToolsWebEnum.proxytunnel: 'proxytunnel',
  KaliToolsWebEnum.qsslcaudit: 'qsslcaudit',
  KaliToolsWebEnum.redsocks: 'redsocks',
  KaliToolsWebEnum.sidguesser: 'sidguesser',
  KaliToolsWebEnum.siege: 'siege',
  KaliToolsWebEnum.skipfish: 'skipfish',
  KaliToolsWebEnum.slowhttptest: 'slowhttptest',
  KaliToolsWebEnum.sqldict: 'sqldict',
  KaliToolsWebEnum.sqlitebrowser: 'sqlitebrowser',
  KaliToolsWebEnum.sqlmap: 'sqlmap',
  KaliToolsWebEnum.sqlninja: 'sqlninja',
  KaliToolsWebEnum.sqlsus: 'sqlsus',
  KaliToolsWebEnum.ssldump: 'ssldump',
  KaliToolsWebEnum.sslh: 'sslh',
  KaliToolsWebEnum.sslscan: 'sslscan',
  KaliToolsWebEnum.sslsniff: 'sslsniff',
  KaliToolsWebEnum.sslsplit: 'sslsplit',
  KaliToolsWebEnum.sslyze: 'sslyze',
  KaliToolsWebEnum.stunnel4: 'stunnel4',
  KaliToolsWebEnum.thcSslDos: 'thc-ssl-dos',
  KaliToolsWebEnum.tlssled: 'tlssled',
  KaliToolsWebEnum.tnscmd10g: 'tnscmd10g',
  KaliToolsWebEnum.uniscan: 'uniscan',
  KaliToolsWebEnum.wafw00f: 'wafw00f',
  KaliToolsWebEnum.wapiti: 'wapiti',
  KaliToolsWebEnum.watobo: 'watobo',
  KaliToolsWebEnum.webacoo: 'webacoo',
  KaliToolsWebEnum.webscarab: 'webscarab',
  KaliToolsWebEnum.webshells: 'webshells',
  KaliToolsWebEnum.weevely: 'weevely',
  KaliToolsWebEnum.wfuzz: 'wfuzz',
  KaliToolsWebEnum.whatweb: 'whatweb',
  KaliToolsWebEnum.wireshark: 'wireshark',
  KaliToolsWebEnum.wpscan: 'wpscan',
  KaliToolsWebEnum.xsser: 'xsser',
  KaliToolsWebEnum.zaproxy: 'zaproxy',
};

extension KaliToolsWebEnumExt on KaliToolsWebEnum {
  String get package {
    switch (this) {
      default:
        return _kaliToolsWebMap[this]!;
    }
  }
}

Future<void> selectKaliToolsWebToInstall() => selectToolsToInstall<KaliToolsWebEnum>(
  groupName: 'kali-tools-web',
  values: KaliToolsWebEnum.values,
  packageNameGetter: (e) => e.package,
);
