name: kali_on_debian
description: A safe and modular way to install Kali Linux tools on any Debian-based system. Easily install Kali Linux hacking tools on Debian-based systems without breaking your setup.
version: 1.0.1
repository: https://github.com/Loschia/kali_on_debian

environment:
  sdk: ^3.8.0
  
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


